# Generated by Django 2.2a1 on 2019-02-24 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acuthon', '0002_auto_20190222_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=32)),
                ('payment_status', models.CharField(max_length=30)),
                ('payment_request_id', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acuthon.Team'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='branch',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acuthon.Payment'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='year',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=3),
        ),
    ]
