# Generated by Django 2.2a1 on 2019-02-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0004_team_team_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
