# Generated by Django 2.2a1 on 2019-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0005_auto_20190225_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_link',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
