# Generated by Django 2.1.3 on 2019-03-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuthon', '0006_auto_20190226_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='theme',
            field=models.CharField(choices=[('NGO APPLICATIONS', 'NGO APPLICATIONS'), ('XR - AR/MR/VR', 'XR - AR/MR/VR'), ('SMART CITY', 'SMART CITY'), ('WOMEN SAFETY', 'WOMEN SAFETY'), ('EDUTAINMENT', 'EDUTAINMENT'), ('INTELLIGENTS APPLICATIONS', 'INTELLIGENTS APPLICATIONS'), ('STARTUP IDEAS', 'STARTUP IDEAS')], max_length=64),
        ),
    ]
